name: CI Bank System C++

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    uses: marianefelix/sistema-bancario/.github/workflows/build.yml@develop
  test:
    uses: marianefelix/sistema-bancario/.github/workflows/test.yml@develop
  generate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create and push tag
        run: |
          TAG_NAME="build-$(date +'%m%d%Y%H%M%S')"
          git tag $TAG_NAME
          git push --tags