name: CI Bank System C++

on:
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Pistache
      run: |
        sudo add-apt-repository ppa:pistache+team/unstable -y
        sudo apt update
        sudo apt install libpistache-dev -y
    
    - name: Set Pistache variable
      run: export LD_LIBRARY_PATH=/path/to/pistache/lib
      
    - name: Build system
      run: make
      
    - name: Run tests
      run: |
        cd tests
        make
        ./testapp
        cd ..
      
    - name: Create tag
      run: |
        sudo apt-get install semver
        LAST_TAG=$(git describe --tags --abbrev=0 || echo "build-0.0.3")
        LAST_VERSION=$(echo $LAST_TAG | sed 's/build-//')
        NEXT_VERSION=$(semver -i patch $LAST_VERSION)
        TAG_NAME="build-$NEXT_VERSION"
        git tag $TAG_NAME
        git push --tags