name: Build and publish a docker image

on:
  workflow_call:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login in Docker Hub Account
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t marianefelix/bank-system:latest .
      - name: Publish Docker Image
        run: |
          docker push marianefelix/bank-system:latest
      - name: Run Docker Container
        run: |
          docker run -p 8080:8080 marianefelix/bank-system:latest