name: Production Release Artifact

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - rel-*

jobs:
  build:
    uses: marianefelix/sistema-bancario/.github/workflows/build.yml@main
  quality:
    uses: marianefelix/sistema-bancario/.github/workflows/quality.yml@main
  test:
    needs: build
    uses: marianefelix/sistema-bancario/.github/workflows/test.yml@main
  generate-artifact:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Archive
        run: |
          git fetch
          git checkout main
          zip -r release.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: release.zip
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login in Docker Hub Account
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t marianefelix/bank-system:latest .
      - name: Publish Docker Image
        run: |
          docker push marianefelix/bank-system:latest
      - name: Run Docker Container
        run: |
          docker run -p 8080:8080 marianefelix/bank-system:latest

