name: CI Bank System C++

on:
  push:
    branches: develop
  pull_request:
    branches: develop
    
env:
  CXX_STANDARD: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        cpp-version: ${{ env.CXX_STANDARD }}
    
    - name: Set up Pistache
      run: |
        sudo add-apt-repository ppa:pistache+team/unstable -y
        sudo apt update
        sudo apt install libpistache-dev -y
    
    - name: Set Pistache variable
      run: export LD_LIBRARY_PATH=/path/to/pistache/lib
      
    - name: Build system
      run: make
      
    - name: Run tests
      run: |
        cd tests
        make
        ./testapp
        cd ..
      
    - name: Create tag
      run: |
        TAG_NAME="build-${{ github.run_number }}"
        git tag $TAG_NAME
        git push --tags