name: Release Candidate Artifact

on:
  push:
    tags:
      - rc-*

jobs:
  build:
    uses: marianefelix/sistema-bancario/.github/workflows/build.yml@main
  quality:
    uses: marianefelix/sistema-bancario/.github/workflows/quality.yml@main
  test:
    needs: build
    uses: marianefelix/sistema-bancario/.github/workflows/test.yml@main
  generate-artifact:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Archive
        run: |
          git fetch
          git checkout release
          zip -r rc.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-candidate-artifact
          path: rc.zip
